// JTG Homepage V2 — Mock data for development
// Minimal runnable dataset for zh-Hans locale

import type { HomepageConfig, UsageTodayResponse } from "./types";

export const MOCK_CONFIG: HomepageConfig = {
  pageMeta: {
    pageName: "home",
    locale: "zh-Hans",
    supportLevel: "full",
    sessionId: "sess_mock_001",
    isLoggedIn: false,
    planTier: "free",
  },
  navBar: {
    logoText: "JTG",
    entries: [
      { key: "before_japan", label: "来日本前", href: "#faq-zone" },
      { key: "renting", label: "在日租住", href: "#faq-zone" },
      { key: "longterm", label: "买房与长住", href: "#faq-zone" },
    ],
    currentLocale: "zh-Hans",
    localeOptions: [
      { code: "zh-Hans", label: "简体中文", shortLabel: "中文" },
      { code: "en", label: "English", shortLabel: "EN" },
      { code: "ja", label: "日本語", shortLabel: "日本語" },
      { code: "ko", label: "한국어", shortLabel: "한국어" },
      { code: "vi", label: "Tiếng Việt", shortLabel: "Tiếng Việt" },
      { code: "th", label: "ภาษาไทย", shortLabel: "ไทย" },
    ],
    helpLink: { label: "有问题找我们", href: "#human-help" },
    accountLink: { label: "升级使用", href: "/contact", visible: true },
  },
  hero: {
    title: {
      line1: "在日本租房生活",
      line2: "有问题，先问这里",
    },
    subtitle: "中日英三语知识库 + AI 问答 + 人工帮助",
    cards: [
      {
        key: "before_japan",
        title: "来日本前",
        description: "签证、找房、初期费用、保证人",
        icon: "plane",
        href: "#faq-zone",
      },
      {
        key: "renting",
        title: "在日租住",
        description: "合同、维修、垃圾分类、邻里沟通",
        icon: "home",
        href: "#faq-zone",
      },
      {
        key: "longterm",
        title: "买房与长住",
        description: "购房流程、贷款、永住权、税务",
        icon: "building",
        href: "#faq-zone",
      },
    ],
  },
  faqZone: {
    categories: [
      { key: "prep", label: "来日准备" },
      { key: "apply_contract", label: "申请与合同" },
      { key: "after_movein", label: "入住之后" },
      { key: "cost_checkout", label: "费用与退房" },
      { key: "buy_longstay", label: "购房与长住" },
    ],
    activeCategoryKey: "prep",
    searchPlaceholder: "搜索问题，例如：押金退还、垃圾分类...",
    searchEmptyState: {
      title: "没有找到相关内容",
      hints: ["试试换个说法", "用关键词而不是长句子", "检查是否有错别字"],
      aiLinkLabel: "试试 AI 问答",
      aiLinkHref: "#ai-zone",
      humanHelpLabel: "联系人工帮助",
      humanHelpHref: "#human-help",
    },
    trendingItems: [
      { id: "t1", label: "押金能退多少", href: "/zh-Hans/faq/renting-security-deposit" },
      { id: "t2", label: "垃圾怎么分类", href: "/zh-Hans/faq/daily-garbage-sorting" },
      { id: "t3", label: "退房提前多久通知", href: "/zh-Hans/faq/renting-lease-renewal" },
      { id: "t4", label: "热水器没热水", href: "/zh-Hans/faq/trouble-no-hot-water" },
      { id: "t5", label: "邻居太吵怎么办", href: "#faq-zone" },
    ],
    cards: [
      {
        id: "renting-initial-cost",
        categoryKey: "prep",
        title: "来日本前需要准备什么材料？",
        summary: "在留资格认定、护照、在留卡、住民登录等必需材料清单。",
        contentTypeLabel: "流程",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-initial-cost",
      },
      {
        id: "renting-guarantor",
        categoryKey: "prep",
        title: "没有日本保证人怎么租房？",
        summary: "使用保证公司（保証会社）替代个人保证人，费用约月租的50-100%。",
        contentTypeLabel: "流程",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-guarantor",
      },
      {
        id: "renting-key-money",
        categoryKey: "apply_contract",
        title: "日本租房初期费用包括哪些？",
        summary: "押金、礼金、中介费、前家赁、火灾保险、保证公司费用明细。",
        contentTypeLabel: "费用",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-key-money",
      },
      {
        id: "renting-lease-renewal",
        categoryKey: "apply_contract",
        title: "租房合同里需要注意什么？",
        summary: "普通借家 vs 定期借家、解约预告期限、更新料、特约条款。",
        contentTypeLabel: "合同",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-lease-renewal",
      },
      {
        id: "daily-garbage-sorting",
        categoryKey: "after_movein",
        title: "垃圾怎么分类？",
        summary: "可燃、不可燃、资源、粗大垃圾四大类，以及各区收集时间。",
        contentTypeLabel: "流程",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/daily-garbage-sorting",
      },
      {
        id: "trouble-no-hot-water",
        categoryKey: "after_movein",
        title: "热水器没有热水怎么办？",
        summary: "检查电源、燃气阀门、水龙头方向。无法解决联系管理公司。",
        contentTypeLabel: "设备",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/trouble-no-hot-water",
      },
      {
        id: "renting-security-deposit",
        categoryKey: "cost_checkout",
        title: "押金退还的合理范围是什么？",
        summary: "正常使用磨损由房东承担，租户只负责故意或过失损坏。",
        contentTypeLabel: "费用",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-security-deposit",
      },
      {
        id: "renting-foreigner-discrimination",
        categoryKey: "cost_checkout",
        title: "退房要提前多久通知？",
        summary: "一般1-2个月，看合同中的解约预告期间。通知必须书面提交。",
        contentTypeLabel: "流程",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/renting-foreigner-discrimination",
      },
      {
        id: "home-buying-foreigner-ownership",
        categoryKey: "buy_longstay",
        title: "外国人可以在日本买房吗？",
        summary: "可以。外国人购房无国籍限制，但贷款条件因身份不同而异。",
        contentTypeLabel: "流程",
        supportLevel: "full",
        machineTranslated: false,
        href: "/zh-Hans/faq/home-buying-foreigner-ownership",
      },
    ],
  },
  trustZone: {
    title: "内容来源与能力说明",
    bullets: [
      "基于日本国土交通省、各区役所官方资料整理",
      "部分内容参考 SUUMO、HOME'S 等公开信息",
      "中文、英文、日语三语由人工审校",
      "韩语、越南语、泰语为机器翻译辅助，仅供参考",
    ],
    officialSourceLink: {
      label: "国土交通省 原状回復ガイドライン",
      href: "https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk3_000026.html",
    },
    languageCompletenessNote:
      "中文/英文/日语内容已人工审校，其他语言为机器翻译辅助版本。",
    disclaimer:
      "本站内容仅供参考，不构成法律意见。具体情况请咨询专业人士或当地相关机构。",
  },
  aiZone: {
    title: "AI 问答",
    description: "用你的语言提问，AI 基于知识库为你解答",
    inputPlaceholder: "输入你的问题...",
    submitLabel: "提问",
    usage: { used: 0, limit: 3, remaining: 3, resetAtText: "明天 00:00 自动重置" },
    disabled: false,
    upgradeHint: { visible: false },
  },
  humanHelp: {
    title: "人工帮助",
    description: "知识库和 AI 无法解决的问题，可以联系我们的团队",
    scenes: [
      "合同条款看不懂，需要解释",
      "和房东/管理公司沟通有困难",
      "退房费用争议",
      "需要日语沟通支援",
    ],
    responseWindowText: "工作日内回复，通常 1-3 个工作日",
    channels: [
      { type: "email", label: "邮件", value: "help@jtg.help", href: "mailto:help@jtg.help" },
      { type: "line", label: "LINE", value: "@jtg-help", href: "https://line.me/R/ti/p/@jtg-help" },
      { type: "form", label: "在线表单", value: "", href: "/contact" },
    ],
    ctaLabel: "联系人工帮助",
    ctaHref: "/contact",
  },
  footer: {
    localeNote: "当前语言：简体中文",
    translationQualityNote: "中文/英文/日语：人工审校 | 韩语/越南语/泰语：机器翻译辅助",
    privacyLink: { label: "隐私政策", href: "/privacy" },
    termsLink: { label: "使用条款", href: "/terms" },
    supportLink: { label: "帮助与反馈", href: "/contact" },
  },
};

export const MOCK_USAGE: UsageTodayResponse = {
  planTier: "free",
  ai: { used: 1, limit: 3, remaining: 2, resetAtText: "明天 00:00 自动重置" },
  bridge: { used: 0, limit: 2, remaining: 2, resetAtText: "明天 00:00 自动重置" },
};
